Benchmark/fe11939/integration
att/qujata pull request #26
Opened 2023-11-13 07:29 UTC by yeudit

cleanup code
improve query results
handle errors
and few more fixes to code

2023-11-15 10:49 UTC, mikekcs reviewed
Api 409 to lock  code 423
Api - check error
Api test_is_running to 
Curl - remove  console.log("this.configService.get('algorithms',[])")
Curl - change 409
Run k8s - remove service account
Run k8s - remove timeout annotations from portal
Run k8s - remove comment in prometheus.yaml

2023-11-16 12:33 UTC, litalmason requested changes

2023-11-16 12:33 UTC, litalmason commented on api/app.py
>      global test_is_running
how come we define this global inside this API? I can also see this var on the top of the page, but not a global var.
Won't
**global** test_is_running = False
on the top of the page work?

2023-11-16 12:33 UTC, litalmason commented on api/app.py
> +    end_time = int(datetime.timestamp(datetime.now() + timedelta(seconds=90)) * 1000)
what is the reason we're adding **90** seconds specifically? and **60** on the start time?

2023-11-16 12:33 UTC, litalmason commented on api/app.py
> +        return jsonify({'error': 'Current test is still running', 'message':'The previous test is still running. Please try again in few minutes'}), 423
423 is very accurate for this error, nice! 
consider using "Constants" for all HTTP codes
For example

LOCKED = 423
BAD_REQUEST = 400

2023-11-16 13:21 UTC, litalmason commented on api/app.py
> +        if(response.status_code < 200 or response.status_code > 299):
I recommend to extract this line
response.status_code < 200 or response.status_code > 299
to a separate function

2023-11-19 08:58 UTC, mikekcs approved these changes

2023-11-19 08:58 UTC, mikekcs commented on api/README.md
> +python3 app.py
This can be run with python 2.x?

2023-11-19 10:10 UTC, mikekcs commented on api/app.py
> +BAD_REQUEST = 400
better to name it something like HTTP_X

2023-11-20 12:06 UTC, litalmason approved these changes

2023-11-20 21:00 UTC, merged